project:
  type: website
  output-dir: docs

website:
  title: "Nebraska R User Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/neb-rug/neb-rug.github.io
      # - about.qmd
  site-url: https://neb-rug.github.io/
  repo-url: https://github.com/neb-rug/neb-rug.github.io
  repo-actions: [edit, source, issue]
  page-footer:
    background: light
    left: "&copy; 2025 Nebraska R User Group. Powered by Quarto."

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



