---
title: "Nebraska R User Group"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sign up for the Nebraska R User Group on [meetup](https://www.meetup.com/neb-rug/).

## Our Events

```{r calendar, warning = FALSE, echo=FALSE, message=FALSE}
# From Heike Hofmann (https://github.com/heike/NebRUG-2024)
source("schedule.R")
class_cal

full_cal |>  
  filter(category!="NA") |> 
  select(date) |> 
  mutate(title = c("Meetup", "Extensions to ggplot2 are easy – right?", "Talking to LLMs Through R", "Creating Beautiful PDFs via HTML/CSS/JS"),
         speaker = c("", "[Heike Hofmann](https://github.com/heike)", "[Matt Waite](https://github.com/mattwaite)", "[Yihui Xie](https://yihui.org/)"),
         link = c("", "[html](https://heike.github.io/NebRUG-2024/2024-12-04-ggplot2-extensions/ggplot2-extensions.html), [pdf](https://heike.github.io/NebRUG-2024/2024-12-04-ggplot2-extensions/ggplot2-extensions.pdf)", "", "[slides](https://slides.yihui.org/2025-pages-litedown.html")) |> 
  knitr::kable(col.names = c("Date", "Title", "Speaker", "Slides"))
```
